import movieOne from '../images/tryPHOTO.jpg';

const movieList = [
  {
    country: '',
    director: '',
    duration: 102,
    year: '',
    description: '',
    image: movieOne,
    trailerLink: '',
    thumbnail: '',
    owner: '',
    movieId: 1,
    nameRU: '33 слова о дизайне',
    nameEN: '',
  },
  {
    country: '',
    director: '',
    duration: 102,
    year: '',
    description: '',
    image: movieOne,
    trailerLink: '',
    thumbnail: '',
    owner: '',
    movieId: 2,
    nameRU: '33 слова о дизайне',
    nameEN: '',
  },
  {
    country: '',
    director: '',
    duration: 102,
    year: '',
    description: '',
    image: movieOne,
    trailerLink: '',
    thumbnail: '',
    owner: '',
    movieId: 3,
    nameRU: '33 слова о дизайне',
    nameEN: '',
  },
  {
    country: '',
    director: '',
    duration: 30,
    year: '',
    description: '',
    image: movieOne,
    trailerLink: '',
    thumbnail: '',
    owner: '',
    movieId: 4,
    nameRU: '33 слова о дизайне',
    nameEN: '',
  },
  {
    country: '',
    director: '',
    duration: 102,
    year: '',
    description: '',
    image: movieOne,
    trailerLink: '',
    thumbnail: '',
    owner: '',
    movieId: 5,
    nameRU: '33 слова о дизайне',
    nameEN: '',
  },
  {
    country: '',
    director: '',
    duration: 102,
    year: '',
    description: '',
    image: movieOne,
    trailerLink: '',
    thumbnail: '',
    owner: '',
    movieId: 6,
    nameRU: '33 слова о дизайне',
    nameEN: '',
  },
  {
    country: '',
    director: '',
    duration: 102,
    year: '',
    description: '',
    image: movieOne,
    trailerLink: '',
    thumbnail: '',
    owner: '',
    movieId: 7,
    nameRU: '33 слова о дизайне',
    nameEN: '',
  },
  {
    country: '',
    director: '',
    duration: 102,
    year: '',
    description: '',
    image: movieOne,
    trailerLink: '',
    thumbnail: '',
    owner: '',
    movieId: 8,
    nameRU: '33 слова о дизайне',
    nameEN: '',
  },
  {
    country: '',
    director: '',
    duration: 102,
    year: '',
    description: '',
    image: movieOne,
    trailerLink: '',
    thumbnail: '',
    owner: '',
    movieId: 9,
    nameRU: '33 слова о дизайне',
    nameEN: '',
  },
  {
    country: '',
    director: '',
    duration: 102,
    year: '',
    description: '',
    image: movieOne,
    trailerLink: '',
    thumbnail: '',
    owner: '',
    movieId: 10,
    nameRU: '33 слова о дизайне',
    nameEN: '',
  },
  {
    country: '',
    director: '',
    duration: 102,
    year: '',
    description: '',
    image: movieOne,
    trailerLink: '',
    thumbnail: '',
    owner: '',
    movieId: 11,
    nameRU: '33 слова о дизайне',
    nameEN: '',
  },
  {
    country: '',
    director: '',
    duration: 102,
    year: '',
    description: '',
    image: movieOne,
    trailerLink: '',
    thumbnail: '',
    owner: '',
    movieId: 12,
    nameRU: '33 слова о дизайне',
    nameEN: '',
  },
  {
    country: '',
    director: '',
    duration: 102,
    year: '',
    description: '',
    image: movieOne,
    trailerLink: '',
    thumbnail: '',
    owner: '',
    movieId: 13,
    nameRU: '33 слова о дизайне',
    nameEN: '',
  },
  {
    country: '',
    director: '',
    duration: 102,
    year: '',
    description: '',
    image: movieOne,
    trailerLink: '',
    thumbnail: '',
    owner: '',
    movieId: 14,
    nameRU: '33 слова о дизайне',
    nameEN: '',
  },
  {
    country: '',
    director: '',
    duration: 102,
    year: '',
    description: '',
    image: movieOne,
    trailerLink: '',
    thumbnail: '',
    owner: '',
    movieId: 15,
    nameRU: '33 слова о дизайне',
    nameEN: '',
  },
  {
    country: '',
    director: '',
    duration: 102,
    year: '',
    description: '',
    image: movieOne,
    trailerLink: '',
    thumbnail: '',
    owner: '',
    movieId: 16,
    nameRU: '33 слова о дизайне',
    nameEN: '',
  },
  {
    country: '',
    director: '',
    duration: 102,
    year: '',
    description: '',
    image: movieOne,
    trailerLink: '',
    thumbnail: '',
    owner: '',
    movieId: 17,
    nameRU: '33 слова о дизайне',
    nameEN: '',
  },
  {
    country: '',
    director: '',
    duration: 102,
    year: '',
    description: '',
    image: movieOne,
    trailerLink: '',
    thumbnail: '',
    owner: '',
    movieId: 18,
    nameRU: '33 слова о дизайне',
    nameEN: '',
  },
  {
    country: '',
    director: '',
    duration: 30,
    year: '',
    description: '',
    image: movieOne,
    trailerLink: '',
    thumbnail: '',
    owner: '',
    movieId: 19,
    nameRU: '33 слова о дизайне',
    nameEN: '',
  },
]

export { movieList };